# Generated by Django 5.0.7 on 2024-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_alter_data_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='password',
        ),
    ]
