# Generated by Django 5.0.7 on 2024-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_remove_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='phone',
            field=models.CharField(default='No data', max_length=10),
            preserve_default=False,
        ),
    ]
