# Generated by Django 5.0.7 on 2024-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_data_city_data_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
